app:
  name: 'simple_user_api'
  version: '1.0.0'

http:
  host: 'localhost'
  port: '8080'

postgres:
  host: 'localhost'
  port: '5432'
  user: 'postgres'
  password: 'xxxxxxx'
  dbname: 'postgres'
  sslmode: 'disable'